[project]
name = "py-qt-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyopengl>=3.1.9",
    "pyopengl-accelerate>=3.1.9",
    "pyqt5>=5.15.11",
]
